[build]
  # The directory to change to before starting a build
  base = "frontend_react"

  # Build command
  command = "CI=false npm run build"  # Adjust this according to your build script

  # Publish directory
  publish = "build"  # Adjust this according to your build output directory
